### ISSUE TITLE
Max line length corner case?

### ISSUE THREAD

**Issue by slacktracer** [prettier/prettier-eslint#66] opened 2017-04-16 15:59 UTC
_Prettier_ then _eslint --fix_ then _max-len_ error.

The following code is perfectly formatted by prettier alone but when eslint _--fixes_ it the maximum line length rule is violated.

```
module.exports = function(x) {
  const sortPlacesByDistance = function sortPlacesByDistance(place_a, place_b) {
    return place_a.distance - place_b.distance;
  };
  sortPlacesByDistance(x);
};
```

.eslintrc.js:
```
module.exports = {
  env: { es6: true, node: true },
  rules: {
    'max-len': [ 'error', 80 ],
    'space-before-function-paren': [ 'error', 'always' ]
  }
};
```

_--fixed_:
```
module.exports = function (x) {

  const sortPlacesByDistance = function sortPlacesByDistance (place_a, place_b) {

    return place_a.distance - place_b.distance;

  };
  sortPlacesByDistance(x);

};
```

Is it even fixable? I mean, it's the fix that breaks it.

Is it the definition of irony...?

**Comment by kentcdodds** [comment] 2017-04-16 16:40
To be clear... The problem is that because you run `prettier` first, it removes the space between the function name `sortPlacesByDistance` and the open paren `(`. Because of this, prettier doesn't do anything more to the function assignment line (normally it would break it down to the next line). Then when you run `eslint --fix` it adds it because you've configured `space-before-function-paren` which will add the space back again and now it's breaking the rule. Because eslint isn't capable of auto-fixing that rule, it remains that way.

It's out of scope for this project to fix an issue like that I'm afraid. You'll just have to change the code so it doesn't do that. This is how you could write it:

```javascript
module.exports = function (x) {
  function sortPlacesByDistance (place_a, place_b) {
    return place_a.distance - place_b.distance;
  };
  sortPlacesByDistance(x);
};
```

or even:

```javascript
module.exports = function(x) {
  const sortPlacesByDistance = function sortPlacesByDistance (placeA, placeB) {
    return placeA.distance - placeB.distance;
  };
  sortPlacesByDistance(x);
};
```

Good luck! Sorry that this is a little too much of an edge case for us to do anything about :-(

**Closed by kentcdodds** 2017-04-16 16:40 UTC

**Comment by slacktracer** [comment] 2017-04-16 17:15
@kentcdodds 

> this is a little too much of an edge case for us to do anything about

I understand. =)

Thank you.
