### ISSUE TITLE
Error generating `parserServices` for eslint plugin `@typescript-eslint`

### ISSUE THREAD

**Issue by r0skar** [prettier/prettier-eslint#201] opened 2019-02-11 11:06 UTC
**Versions**:

- `prettier-eslint` version: 8.8.2
- `node` version: 11.9.0
- `yarn` version: 1.13.0

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

`.eslintrc.js`

```javascript
parser: `@typescript-eslint/parser`,
parserOptions: {
  project: `./tsconfig.json`
},
rules: {
  '@typescript-eslint/no-unnecessary-type-assertion': 2
}
```

**What I did:**
Run prettier (via VSCode`s FormatOnSave hook).

**What happened:**

```
Error while loading rule '@typescript-eslint/no-unnecessary-type-assertion'/home/oskar/dev/hyperapp/hyper-parcel/src/bootstrap.ts:: You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

**Problem description:**

Running `prettier-eslint` I get the error above. Running `eslint` directly gives no errors and works as expected. I have also tried it with an absolute path to my `tsconfig.json`, but the error is the same.

**Reproduction repository:**
https://github.com/r0skar/prettier-eslint-test

**Comment by r0skar** [comment] 2019-02-11 15:11
I have created a quick test repo: https://github.com/r0skar/prettier-eslint-test

If you open it in VSCode with the prettier extension installed, you will get an error upon saving `index.ts`, but running `yarn eslint` will not show any error.

**Comment by xinshangshangxin** [comment] 2019-02-13 08:46
when i use `.eslintrc.js` with 
```
parser: '@typescript-eslint/parser',
plugins: ['@typescript-eslint'],
```

I directly [remove code](https://github.com/prettier/prettier-eslint/blob/master/src/index.js#L125-L127)
```ts
formattingOptions.eslint.parser = require.resolve(
      "typescript-eslint-parser"
    );
```

it work fine

**Comment by zimme** [comment] 2019-02-13 09:04
I'm looking into this today.

**Comment by NewFuture** [comment] 2019-02-15 12:35
update `typescript-eslint-parser`  (Deprecated)  to  `@typescript-eslint/parser`

**Comment by joefiorini** [comment] 2019-03-21 16:05
Ideally this would be fixed by #197, but it sounds like it's blocked by some necessary changes to the testing infrastructure. In the meantime, would it be possible update this library to use `@typescript/eslint-parser` instead of the deprecated `typescript-eslint-parser`? @zimme @r0skar Would you accept a PR for this kind of change or would it run into the same issue as #197?

**Comment by OliverJAsh** [comment] 2019-04-26 11:28
The main suggestion here seems to be to update from the old `typescript-eslint-parser` to the new `@typescript-eslint/parser`.

However, I would like to make another suggestion: make `prettier-eslint` respect any predefined TS parsers (via an existing `parser` option in the ESLint RC).

This way, users may user/specify their own version of the TS parser, in much the same way that `prettier-eslint` allows users to use/specify their own version of ESLint.

**Comment by MaxMilton** [comment] 2019-05-15 00:50
It's surprising to me that the user config is mangled.

Wouldn't the optimal solution to this be _not_ to override the user configured parser/s at all? If users want the ability to parse a particular file type they can simply add the `parser` + relevant `overrides`. That way they can also add `parserOptions` correctly.

Keeping the functional scope of the extension tighter would be nice too (less dependencies, etc.).

**Comment by zimme** [comment] 2019-05-15 05:36
@MaxMilton It's most likely an oversight when typescript support was added to not keep `parser`/`parserOptions` when handling typescript files.

**Comment by zyy7259** [comment] 2019-06-26 09:19
I think this issue has been solved by [the release of prettier-eslint v9.0.0](https://github.com/prettier/prettier-eslint/releases/tag/v9.0.0).

**Closed** 2019-06-26 09:52 UTC

**Comment by OliverJAsh** [comment] 2019-06-26 10:30
Confirmed it fixes my issue (https://github.com/prettier/prettier-eslint/issues/207)

**Comment by ricardolpd** [comment] 2021-05-13 17:09
could anyone provide an example of a config that provides a work around for this? We are facing this issue with `'@typescript-eslint/require-await'` in our mono repo.

**Comment by m-cat** [comment] 2021-08-18 17:33
@ricardolpd I was able to fix this by adding `"project": ["tsconfig.json"],`:

```json
"parserOptions": {
  "ecmaVersion": 2020,
  "project": ["tsconfig.json"] ,
  "sourceType": "module"
},
```

**Comment by vincenzon** [comment] 2022-02-15 10:53
@m-cat that didn't work for me. We are also seeing this trying to add the same require-await rule as @ricardolpd. Are there any other suggestions on how to fix this?

**Comment by mikeaustin** [comment] 2023-10-11 23:16
For me, the issue was that the parserOptions.project was not looking in the current project of a mono-repo. I had to specify it as if it was from the top of the repo.

packages/react-desktop/package.json

```
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ],
    "parserOptions": {
      "project": "./react-desktop/tsconfig.json"
    },
    "rules": {
      "@typescript-eslint/strict-boolean-expressions": "error"
    },
```

I'm not sure if that is a bug or not. It seems strange the . is the repo root, not the current project root. Now I can avoid those pesky falsyness in conditionals.

The requirement for the "parserOptions.project" property was seen after running `npx eslint . --ext .ts`

```
Error: Error while loading rule '@typescript-eslint/strict-boolean-expressions': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

**Comment by adketuri** [comment] 2024-01-22 22:48
Adding another solution since I found this thread via google. We also had a monorepo and the necessary parserOptions.project property was set correctly. The stack trace pointed to a `jest.config.js` file it was trying to lint, I explicitly ignored that file in my `.eslintrc.js`:

```
ignorePatterns: ["jest.config.js", "node_modules/", "dist/"],
```
