### ISSUE TITLE
no-console will not throw error, but just nothing...

### ISSUE THREAD

**Issue by JackieLs** [prettier/prettier-eslint#561] opened 2021-05-31 12:27 UTC
**Versions**:

- `prettier-eslint` version: 9.0.2
- `node` version: 14.17.0
- `npm` (or `yarn`) version: 6.14.13

English not good

In eslint rules, the property `fixable` of `no-console`  is `undefined`.
The function `getRelevantESLintConfig` in `prettier-eslint/src/utils.js`
```js
....
if (loadedRules.has(name)) {
  const {
    meta: { fixable }
  } = loadedRules.get(name);

  if (!fixable) {
    logger.trace('turing off rule:', JSON.stringify({ [name]: rule }));
    rule = ['off'];
  }
}
...
```
I think the realization changing 'error' to 'off' is not very good.
Although it's unfixable, but eslint will hint the error, but prettier-eslint not.

I would like commit one pr.

**Comment by JounQin** [comment] 2022-08-15 04:10
Duplicate of #704 and PR welcome

**Closed by JounQin** 2022-08-15 04:10 UTC
