### ISSUE TITLE
.eslintignore not being found?

### ISSUE THREAD

**Issue by lifeiscontent** [prettier/prettier-eslint#67] opened 2017-04-17 06:40 UTC
When running prettier-atom it doesn't seem .eslintignore is being used as it still runs on directories I've ignored.

**Comment by kentcdodds** [comment] 2017-04-17 14:57
Hmmm... I've not noticed this. Could you create a repository to reproduce this issue? And maybe dig a little bit to figure out what's going on?

**Comment by alexpchin** [comment] 2017-11-04 14:46
I also think this is happening.

**Comment by zimme** [comment] 2017-11-28 22:36
I believe I've found the cause of this. Will look into it a bit more and see if I can get a fix out.

**Comment by zimme** [comment] 2017-12-04 18:27
Ok, I looked into this a bit more and I can't really find a bug here. I thought I found one but I was mistaken.

The way this works now is that even if a file is ignored in `.eslintignore` it will still be ran through `prettier`, however it should be ignored by `eslint`.

I will need a reprod to be able to fix this problem and I'll close this issue in a few weeks if I haven't gotten a reprod by then.

**Comment by zimme** [comment] 2018-01-17 21:51
Closing this as no one has been able to provide a reproduction.

**Closed by zimme** 2018-01-17 21:51 UTC
Labels: help wanted, needs investigation
