### ISSUE TITLE
given .eslintrc in filePath is not the only one considered - but also current and user folder's

### ISSUE THREAD

**Issue by cancerberoSgx** [prettier/prettier-eslint#148] opened 2017-12-09 00:21 UTC
around line 224 of index.js you are calling `const config = configFinder.getConfigForFile(filePath);` which ends up calling eslint/lib/config.js#getConfig() method

What I can see is that this method will compute the configuration not only using the given config file but also the current project config file, user's config and probably other .eslintrc in the system. 

In my case the manifested bug is that a .eslintrc file that doesn't define a rule and should take the default value will nevertheless be defaulted with my current project .eslintrc (or could be my user's .eslintrc). 

If I set a 'filePath' in prettier-eslint I expect that only the rules defined there are applied and the others take default values. If this is how prittier-eslint should work then I think for this particular project this is causing lots of issues. But maybe you disagree?

I also tried to illustrate the issue by taking a screenshot of a breakpoint in the eslint/lib/config.js#getConfig() and printing the vector variable that contains more than one .eslintrc - the given one and another one that is in my local project - they are all merged and I think that shound't happen

![screenshot_2017-12-08_21-11-44](https://user-images.githubusercontent.com/112746/33790271-82eab186-dc5d-11e7-941f-169f6fbfadc3.png)

I just starting using pretties-eslint and is very very cool - will keep investigating the issue and try to pull request a solution - could take me a while since. But keep tit up !!! :) 

BTW - I'm developing a gallery of what code looks like using different popular eslint-configs here: https://cancerberosgx.github.io/prettier-eslint-gallery/gallery/

The idea is to compare eslint --fix with prettier-eslint and also (TODO) to generate reports of how well both formatters do the job fixing applying each the config

Versions I'm using :

node: 9.2.0
"babel-eslint": "^8.0.3",
    "eslint": "^4.12.1",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-config-google": "^0.9.1",
    "eslint-config-gulp": "^2.1.0",
    "eslint-config-hapi": "^11.1.0",
    "eslint-config-mdcs": "^4.2.2",
    "eslint-config-standard": "^10.2.1",
    "eslint-config-walmart": "^2.2.0",
    "eslint-config-xo": "^0.19.0",
    "eslint-plugin-filenames": "^1.2.0",
    "eslint-plugin-hapi": "^4.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-node": "^5.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-react": "^7.5.1",
    "eslint-plugin-standard": "^3.0.1",
    "handlebars": "^4.0.11",
    "prettier-eslint": "^8.2.5",

**Comment by zimme** [comment] 2017-12-12 20:44
I've seen that there is some unexpected behaviour when it comes to the ordering of config override, but I haven't had time to look into it in depth yet.

My initial thoughts on this is that I don't really see the behaviour about finding a config up the chain of folders, etc. being something that I'll change as we're using eslint's getConfig functionality and the same goes for prettier. However there might be some changes coming on how the configs are overridden, i.e. config provided via api will override that of a config file etc.

**Comment by cancerberoSgx** [comment] 2017-12-12 20:53
OK, I agree that the better approach is to use eslint apis . This is more a heads up for you. Imagine I have a .eslintrc in the local folder or in my user's folder and I'm using prettier-eslint to format a file targeting different eslint-config files just to see how the style looks like. In that case, the behavior I'm seeing is that if the target eslint dont define a rule it will inherith durrect/user folder's eslint-config ones. But since this is the standard behavior of eslint I agree with you prettier-eslint should behave the same. Feel free to close the issue (I can't) - perhaps also you could mention this fact in the readme - but I don't think it's so important. Thanks

**Comment by zimme** [comment] 2017-12-21 21:26
From what I can tell, this is working as expected and I'm relying on `eslint`s api for getting the config and can't affect this in some way in this package without writing my own logic for resolving the config, which isn't an option.

Closing this as it's not really a but, but I'm open for further discussion if it's needed.

**Comment by zimme** [comment] 2017-12-21 21:29
Actually, I'm re-opening this.

What I've thought about and probably will do in a new major version is change the config merging when `eslintConfig` is provided as an option. i.e. you specify which eslintConfig you want to use.

I need to think about this a bit more, it's kinda related to using this package in editor integrations and in the cli.

**Comment by westmark** [comment] 2018-01-02 13:54
@zimme Could this be related to https://github.com/prettier/prettier-atom/issues/334 ?

**Comment by zimme** [comment] 2018-01-02 14:02
Yes, they are related. But it's because of the way we handle provided configuration and merge that with configuration we read from file.

I've been thinking about changing this behaviour, but it's a breaking change so before we make that change I need to make sure the "new" solution can handle all the use cases otherwise the change seems unnecessary.

**Comment by zimme** [comment] 2018-01-17 21:42
Closing this as it's working as intended, i.e. we rely on eslint's own config resolving and I won't be implementing my own.

**Closed by zimme** 2018-01-17 21:42 UTC
Labels: needs investigation
