### ISSUE TITLE
Rule "quotes": ["error", "backtick"] causes errors

### ISSUE THREAD

**Issue by 0x80** [prettier/prettier-eslint#75] opened 2017-04-27 22:30 UTC
If I use this rule

`"quotes": ["error", "backtick"]`

I get errors like this
```
prettier-eslint [ERROR]: prettier formatting failed due to a prettier error
prettier-eslint-cli [ERROR]: There was an error formatting "packages/gatsby/lib/utils/webpack.config.js": 
    ● Validation Error:

      Option "singleQuote" must be of type:
        boolean
      but instead received:
        string

      Example:
      {
        "singleQuote": false
      }
```

Using prettier-eslint-cli 3.4.2

**Comment by lemon79** [comment] 2017-04-27 23:58
this shouldn't have happened, let me install eslint and check

**Comment by kentcdodds** [comment] 2017-04-28 02:17
I added a section in the README that should help you find out what the problem is: [debugging](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)

**Comment by lemon79** [comment] 2017-04-28 05:46
Thank you!!

**Comment by 0x80** [comment] 2017-04-28 09:05
I ran it with trace. The inferred eslint options contain

```json
"quotes": Array [
        "error",
        "backtick",
      ],
```

But the options then passed to prettier by prettier-eslint are
```json
"prettierOptions": Object {
    "bracketSpacing": false,
    "parser": "babylon",
    "printWidth": 80,
    "semi": false,
    "singleQuote": "backtick",
    "tabWidth": 2,
    "trailingComma": "es5",
    "useTabs": false,
  },
```

Since prettier expects a boolean for singleQuote this breaks like the error suggested

**Comment by 0x80** [comment] 2017-04-28 10:10
I created this PR #76 

Although I can't figure out how to test it. If I install it from my github branch the binary doesn't seem to pick up the new code.

BTW The trace mode brings my computer to its knees when I use it on a glob pattern matching a bunch or files. Might be worth mentioning that it's better run on a single file. And I wonder if the long stack traces are necessary. They pollute the output a lot.

**Comment by kentcdodds** [comment] 2017-04-28 16:52
Merged. Thanks!

> And I wonder if the long stack traces are necessary? They pollute the output quite a bit.

That's kind of the point though. You can also use `debug` instead of `trace`. Thanks for the feedback. I added a note about only running it on one :)

Thanks again!

**Closed by kentcdodds** 2017-04-28 16:52 UTC
